# Generated by Django 4.1.7 on 2023-09-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_category'),
        ('store', '0006_product_orginalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_product', to='accounts.category'),
        ),
    ]
