# Generated by Django 4.1.7 on 2023-09-06 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_category'),
        ('store', '0007_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='product_image')),
                ('model', models.CharField(max_length=100)),
                ('ram', models.CharField(choices=[('4GB', '4GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('24GB', '24GB'), ('32GB', '32GB')], default='8GB', max_length=20)),
                ('hard_disk', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD')], default='SSD', max_length=50)),
                ('rom', models.CharField(max_length=20)),
                ('processor', models.CharField(max_length=100)),
                ('generation', models.CharField(choices=[('7th Gen', '7th Gen'), ('8th Gen', '8th Gen'), ('9th Gen', '9th Gen'), ('10th Gen', '10th Gen'), ('11th Gen', '11th Gen'), ('12th Gen', '12th Gen'), ('13th Gen', '13th Gen')], default='12th Gen', max_length=20)),
                ('graphic_card', models.CharField(max_length=100)),
                ('operating_system', models.CharField(choices=[('Windows 7', 'Windows 7'), ('Windows 8', 'Windows 8'), ('Windows 10', 'Windows 10'), ('Windows 11', 'Windows 11'), ('Windows 12', 'Windows 12'), ('Ubantu', 'Ubantu'), ('Linux', 'Linux')], default='Windows 12', max_length=100)),
                ('screensize', models.CharField(choices=[('11.6 inch', '11.6 inch'), ('12 inch', '12 inch'), ('13.3 inch', '13.3 inch'), ('14 inch', '14 inch'), ('15.6 inch', '15.6 inch'), ('17 inch', '17 inch')], default='15.6 inch', max_length=100)),
                ('warranty', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('orginalprice', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_l', to='accounts.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
